#This file is to create our own image which contains all diff images details

#FROM <imagename> : We are taking ubuntu image as base image and add other on top of it
#FROM scratch  : We are creating an empty image and will add other image on top of it https://hub.docker.com/_/scratch
FROM ubuntu

MAINTAINER sheetal singh <sheetal0123@gmail.com>

#RUN command get executed while building base image
RUN apt-get update

#CMD command get executed once all images are ready and downloaded 
CMD ["echo","Hellow World...."]